include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for Mesh Manager
LUCI_DEPENDS:=+luci-base +rpcd +rpcd-mod-file +jsonfilter +curl +iwinfo +hostapd-common +hostapd-utils +uhttpd
LUCI_PKGARCH:=all
PKG_VERSION:=1.1.0
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk
