include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for WAN Policy & Interface Watchdog
LUCI_DEPENDS:=+luci-base +pbr +ip-full +rpcd
LUCI_PKGARCH:=all
PKG_VERSION:=2.1.0
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
