include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for WAN Policy & Interface Watchdog
LUCI_DEPENDS:=+luci-base \
	+pbr \
	+ip-full \
	+rpcd

PKG_LICENSE:=GPL-2.0-or-later
PKG_MAINTAINER:=CHUNGPT17

PKG_VERSION:=v2.1.0
PKG_RELEASE:=1

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
